[features]
seeds = false
skip-lint = false
[programs.localnet]
gm_anchor = "5vN1TJXtrms8qc9MEh8iQXwRe7DhiqV7bS8bHvEhUvth"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/vincentleow/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
